### ISSUE TITLE
Former EU isle listed twice

### ISSUE THREAD

**Issue by thaJeztah** [vbatts/emojisum#1]
These _look_ pretty similar;

<img width="443" alt="screen shot 2016-12-03 at 11 48 54" src="https://cloud.githubusercontent.com/assets/1804568/20858853/ce8084c8-b94e-11e6-852e-97952827e45c.png">

https://github.com/vbatts/emojisum/blob/master/main.go#L271
https://github.com/vbatts/emojisum/blob/master/main.go#L423

Maybe use a :eu: or 🐳 (:innocent:)

**Comment by vbatts** [comment]
Good catch. They weren't listed next to each other.

**Comment by thaJeztah** [comment]
😃 Thanks! 👍
